### PR TITLE
ci: Build server tests earlier

### PR DESCRIPTION
**Pull request by svix-jplatte**
- Counts test build time against the build step
- Aborts earlier in case tests fail to build

### CODE REVIEW

**Comment by svix-jplatte** [comment]
I was kind of expecting it. Looks like bridge CI failure is not because of any changes I made. :unamused:

**Comment by svix-jplatte** [comment]
Seems like this consistently breaks tests, despite being such a trivial change :thinking:

**Comment by svix-onelson** [comment]
> Seems like this consistently breaks tests, despite being such a trivial change 🤔
> But this PR is sufficiently un-important that this doesn't need to be figured out now.

I'm not sure it would behave differently, but `cargo test --no-run` should produce all the test binaries without running the tests. I just don't know if a subsequent `cargo test` will reuse those pre-built binaries in this situation, or if we'd have to invoke them each ourselves.

**Comment by svix-jplatte** [comment]
Interesting idea, unfortunately the outcome is the same. I've backed out the bridge change, should still be worth to merge for server.

**Review by svix-onelson — APPROVED** [review]

**Pull request merged**
