### PR TITLE
Libs: Add GetOrCreate function for Application API

### LINKED ISSUE #224: Get-or-create app support for all languages

### PR DESCRIPTION
**Pull request by svix-stephanie**
## Motivation

Based on previous changes to Python, now adding support to the other
libraries for get-or-create

Fixes #224 

## Solution

- All languages: Use the get_or_create binding

### CODE REVIEW

**Comment by tasn** [comment]
These seem like completely unrelated changes. Can you please split them to separate PRs?

**Comment by maitham** [comment]
Can't wait for channel filter's, would help out our users a lot!

**Comment by tasn** [comment]
In addition to my previous comment; this PR changes A LOT of formatting, this is not good and makes it impossible to review.

Speak to @svix-frank on what to do, but if you absolutely must reformat (and Frank agrees), do it in a separate PR.

**Comment by fcjr** [comment]
> his PR changes A LOT of formatting

@svix-stephanie it looks like you ran `go fmt` on all the generated files.  Though the new formatting is technically correct, lets undo these changes.  We chose not to format these files as we did not want to require go to be installed in order to update the internal generated files.

**Comment by tasn** [comment]
Should this be closed? (replaced by another PR already?) or is it still live?

**Review by svix-frank — APPROVED** [review]

**Pull request merged**
