### PR TITLE
implement clone derive macro for Sivx client

### PR DESCRIPTION
**Pull request by imabdulbasit**
## Motivation
Configuration struct derives clone macro so Sivx struct can also derive it. This would be helpful to clone Sivx client when sharing it between threads without wrapping it in Arc.

## Solution
Add Clone derive macro

### CODE REVIEW

**Comment by tasn** [comment]
I'm not against cloning it per-se, but it feels wasteful to clone it and all of the inner structure for it. I almost feel like if you want to do it, we should at least have the inner object wrapped in an Arc, no?

**Comment by imabdulbasit** [comment]
> I'm not against cloning it per-se, but it feels wasteful to clone it and all of the inner structure for it. I almost feel like if you want to do it, we should at least have the inner object wrapped in an Arc, no?

Inner structure also has Clone implemented :)

**Comment by tasn** [comment]
There's a `Configuration` structure, no? It probably includes multiple things in it.

**Comment by imabdulbasit** [comment]
> There's a `Configuration` structure, no? It probably includes multiple things in it.

Yes but Configuration structure implements Clone so Svix struct can also implement clone

**Comment by tasn** [comment]
Yeah, but that's what I'm saying, it ends up cloning the whole Configuration structure...

Anyhow, I can go either way. @svix-gabriel, do you have any thoughts on this?

**Comment by svix-gabriel** [comment]
I definitely see the value in implementing `Clone`, but I agree with the suggestion that this should wrap the Configuration struct in an `Arc<...>` internally. `Clone` will be more performant if it's just incrementing a reference count, rather than copying all of the underlying strings and other configuration data.

**Comment by svix-jplatte** [comment]
Superseded by  #1493.

**Pull request closed without merging**
