### PR TITLE
Add some Python client tests

### PR DESCRIPTION
**Pull request by anlambert**
This PR adds some unit tests for the Svix Python OpenAPI client to avoid breaking things (see https://github.com/svix/svix-webhooks/issues/1440).

This is still a work in progress, I just added a couple of simple tests but one of them showcases the issue mentioned above (see [Github Actions job report](https://github.com/anlambert/svix-webhooks/actions/runs/10890896022/job/30220613317) for newly added workflow).

### CODE REVIEW

**Review by svix-jplatte — COMMENTED** [review]
Hey, thanks for the PR!

We'd be glad to have more unit tests, so please do add anything that you feel makes sense. Doesn't all have to be one PR either, but of course I'll honor your preference w.r.t. PR setup and will wait for the draft state to be removed before merging.

Also, I just noticed when reviewing the workflow file that there's some weird thing in there that you seem to have copied from our existing python lint workflows. Would you mind applying the changes from #1445 to the new workflow file? Specifically, I'm talking about the workflow trigger rules, and the version of the `setup-python` action.

**Comment by anlambert** [comment]
> We'd be glad to have more unit tests, so please do add anything that you feel makes sense. Doesn't all have to be one PR either, but of course I'll honor your preference w.r.t. PR setup and will wait for the draft state to be removed before merging.

Great, I do not intend to cover all the Python OpenAPI code but adding a couple of simple tests on the most used features (notably sending messages) should be sufficient to avoid bad surprises in the future. I will try to finish that work y the end of the week. 

> Also, I just noticed when reviewing the workflow file that there's some weird thing in there that you seem to have copied from our existing python lint workflows. Would you mind applying the changes from https://github.com/svix/svix-webhooks/pull/1445 to the new workflow file? Specifically, I'm talking about the workflow trigger rules, and the version of the setup-python action.

Sure.

**Comment by svix-jplatte** [comment]
I see you force-pushed a few times, is this still work in progress?

**Comment by anlambert** [comment]
> I see you force-pushed a few times, is this still work in progress?

Sorry, I got delayed on this but I think it is ready for review. 

This PR does not cover the whole Svix Python OpenAPI client features but I think it should be enough to catch any important breakages that could be introduced.

I am going to rebase it to the  main branch and mark it ready for review.

**Comment by anlambert** [comment]
> I am going to rebase it to the main branch and mark it ready for review.

Done !

**Pull request merged**
